query GetOneTodos($id: String!) {
    oneTodo (id: $id) {
        ...TodoInfo
    } 
}

query AllTodos {
    allTodos {
        ...TodoInfo
    }
}

# query TodosByUser($userid: String!) {
#     todosByUser(userid:$userid) {
#         ...TodoInfo
#     }
# }

# mutation MutateTodos ($id: String!, $input: String!) {
#     addTodo (input: $input) {
#         ...TodoInfo
#     }
#     deleteTodo (id: $id)
#     updateComplete (id: $id) {
#         ...TodoInfo
#     }
# }

mutation AddTodo ($input: String!, $userid: String!) {
    addTodo (input: $input, userid: $userid) {
        ...TodoInfo
    }
}

mutation UpdateComplete ($id: String!) {
    updateComplete (id: $id) {
        ...TodoInfo
    }
}

mutation DeleteTodo ($id: String!) {
    deleteTodo (id: $id) {
        ...TodoInfo
    }
}